apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/GreetaPearlNuvepro/eks-gitops-pipeline
    targetRevision: main
    path: helm/order-service

    helm:
      releaseName: order-service
      valueFiles:
        - ../../gitops/environments/prod/values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: order-service-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
